# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbevents',
            options={'ordering': ['-Start_Time']},
        ),
    ]
