# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160907_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tangocommunityinfo',
            name='email',
            field=models.CharField(blank=True, max_length=928, null=True),
        ),
    ]
