# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160911_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbevents',
            options={'ordering': ['-Start_Time']},
        ),
        migrations.AlterField(
            model_name='fblocation',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
