# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20160914_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbevents',
            name='Event_Id',
            field=models.CharField(max_length=200),
        ),
    ]
