# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20160916_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tango_events',
            name='category',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='profiles.Tango_Location', unique=True),
        ),
    ]
