# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20160916_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fblocation',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tango_location',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
