# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20160916_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbevents',
            name='Location_Name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
