# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20161113_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbevents',
            name='Location_Name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
