# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20161113_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbevents',
            name='Location_Name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
